// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"comment/internal/biz"
	"comment/internal/conf"
	"comment/internal/data"
	"comment/internal/server"
	"comment/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	CommentRepo := data.NewCommentRepo(dataData, logger)
	CommentUsecase := biz.NewCommentUseCase(CommentRepo, logger)
	CommentService := service.NewCommentService(CommentUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, CommentService, logger)
	grpcServer := server.NewGRPCServer(confServer, CommentService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
