// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: api/praise/praise.proto

package praise

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddPraiseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid          int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	RelationType int32 `protobuf:"varint,3,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"`
	RelationId   int32 `protobuf:"varint,2,opt,name=relation_id,json=relationId,proto3" json:"relation_id,omitempty"`
}

func (x *AddPraiseRequest) Reset() {
	*x = AddPraiseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_praise_praise_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPraiseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPraiseRequest) ProtoMessage() {}

func (x *AddPraiseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_praise_praise_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPraiseRequest.ProtoReflect.Descriptor instead.
func (*AddPraiseRequest) Descriptor() ([]byte, []int) {
	return file_api_praise_praise_proto_rawDescGZIP(), []int{0}
}

func (x *AddPraiseRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AddPraiseRequest) GetRelationType() int32 {
	if x != nil {
		return x.RelationType
	}
	return 0
}

func (x *AddPraiseRequest) GetRelationId() int32 {
	if x != nil {
		return x.RelationId
	}
	return 0
}

type AddPraiseReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *AddPraiseReply) Reset() {
	*x = AddPraiseReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_praise_praise_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPraiseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPraiseReply) ProtoMessage() {}

func (x *AddPraiseReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_praise_praise_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPraiseReply.ProtoReflect.Descriptor instead.
func (*AddPraiseReply) Descriptor() ([]byte, []int) {
	return file_api_praise_praise_proto_rawDescGZIP(), []int{1}
}

func (x *AddPraiseReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AddPraiseReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CancelPraiseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid          int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	RelationType int32 `protobuf:"varint,3,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"`
	RelationId   int32 `protobuf:"varint,2,opt,name=relation_id,json=relationId,proto3" json:"relation_id,omitempty"`
}

func (x *CancelPraiseRequest) Reset() {
	*x = CancelPraiseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_praise_praise_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelPraiseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPraiseRequest) ProtoMessage() {}

func (x *CancelPraiseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_praise_praise_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPraiseRequest.ProtoReflect.Descriptor instead.
func (*CancelPraiseRequest) Descriptor() ([]byte, []int) {
	return file_api_praise_praise_proto_rawDescGZIP(), []int{2}
}

func (x *CancelPraiseRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CancelPraiseRequest) GetRelationType() int32 {
	if x != nil {
		return x.RelationType
	}
	return 0
}

func (x *CancelPraiseRequest) GetRelationId() int32 {
	if x != nil {
		return x.RelationId
	}
	return 0
}

type CancelPraiseReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CancelPraiseReply) Reset() {
	*x = CancelPraiseReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_praise_praise_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelPraiseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPraiseReply) ProtoMessage() {}

func (x *CancelPraiseReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_praise_praise_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPraiseReply.ProtoReflect.Descriptor instead.
func (*CancelPraiseReply) Descriptor() ([]byte, []int) {
	return file_api_praise_praise_proto_rawDescGZIP(), []int{3}
}

func (x *CancelPraiseReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CancelPraiseReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type IsPraisePraiseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uids         string `protobuf:"bytes,1,opt,name=uids,proto3" json:"uids,omitempty"`
	RelationType int32  `protobuf:"varint,3,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"`
	RelationId   int32  `protobuf:"varint,2,opt,name=relation_id,json=relationId,proto3" json:"relation_id,omitempty"`
}

func (x *IsPraisePraiseRequest) Reset() {
	*x = IsPraisePraiseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_praise_praise_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsPraisePraiseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsPraisePraiseRequest) ProtoMessage() {}

func (x *IsPraisePraiseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_praise_praise_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsPraisePraiseRequest.ProtoReflect.Descriptor instead.
func (*IsPraisePraiseRequest) Descriptor() ([]byte, []int) {
	return file_api_praise_praise_proto_rawDescGZIP(), []int{4}
}

func (x *IsPraisePraiseRequest) GetUids() string {
	if x != nil {
		return x.Uids
	}
	return ""
}

func (x *IsPraisePraiseRequest) GetRelationType() int32 {
	if x != nil {
		return x.RelationType
	}
	return 0
}

func (x *IsPraisePraiseRequest) GetRelationId() int32 {
	if x != nil {
		return x.RelationId
	}
	return 0
}

type IsPraisePraiseReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *IsPraisePraiseReply) Reset() {
	*x = IsPraisePraiseReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_praise_praise_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsPraisePraiseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsPraisePraiseReply) ProtoMessage() {}

func (x *IsPraisePraiseReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_praise_praise_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsPraisePraiseReply.ProtoReflect.Descriptor instead.
func (*IsPraisePraiseReply) Descriptor() ([]byte, []int) {
	return file_api_praise_praise_proto_rawDescGZIP(), []int{5}
}

func (x *IsPraisePraiseReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *IsPraisePraiseReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type AddPraiseReplyData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *AddPraiseReplyData) Reset() {
	*x = AddPraiseReplyData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_praise_praise_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPraiseReplyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPraiseReplyData) ProtoMessage() {}

func (x *AddPraiseReplyData) ProtoReflect() protoreflect.Message {
	mi := &file_api_praise_praise_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPraiseReplyData.ProtoReflect.Descriptor instead.
func (*AddPraiseReplyData) Descriptor() ([]byte, []int) {
	return file_api_praise_praise_proto_rawDescGZIP(), []int{1, 0}
}

func (x *AddPraiseReplyData) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type CancelPraiseReplyData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *CancelPraiseReplyData) Reset() {
	*x = CancelPraiseReplyData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_praise_praise_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelPraiseReplyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPraiseReplyData) ProtoMessage() {}

func (x *CancelPraiseReplyData) ProtoReflect() protoreflect.Message {
	mi := &file_api_praise_praise_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPraiseReplyData.ProtoReflect.Descriptor instead.
func (*CancelPraiseReplyData) Descriptor() ([]byte, []int) {
	return file_api_praise_praise_proto_rawDescGZIP(), []int{3, 0}
}

func (x *CancelPraiseReplyData) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type IsPraisePraiseReplyData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int64 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	IsPraise bool  `protobuf:"varint,4,opt,name=isPraise,proto3" json:"isPraise,omitempty"`
}

func (x *IsPraisePraiseReplyData) Reset() {
	*x = IsPraisePraiseReplyData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_praise_praise_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsPraisePraiseReplyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsPraisePraiseReplyData) ProtoMessage() {}

func (x *IsPraisePraiseReplyData) ProtoReflect() protoreflect.Message {
	mi := &file_api_praise_praise_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsPraisePraiseReplyData.ProtoReflect.Descriptor instead.
func (*IsPraisePraiseReplyData) Descriptor() ([]byte, []int) {
	return file_api_praise_praise_proto_rawDescGZIP(), []int{5, 0}
}

func (x *IsPraisePraiseReplyData) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *IsPraisePraiseReplyData) GetIsPraise() bool {
	if x != nil {
		return x.IsPraise
	}
	return false
}

var File_api_praise_praise_proto protoreflect.FileDescriptor

var file_api_praise_praise_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x61, 0x69, 0x73, 0x65, 0x2f, 0x70, 0x72, 0x61,
	0x69, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x72, 0x61, 0x69, 0x73, 0x65, 0x22, 0x6a, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x50, 0x72, 0x61, 0x69,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x72,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0c, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x22, 0x4e, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x1a, 0x16, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f,
	0x6b, 0x22, 0x6d, 0x0a, 0x13, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x50, 0x72, 0x61, 0x69, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0c, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x22, 0x51, 0x0a, 0x11, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x1a, 0x16, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x02, 0x6f, 0x6b, 0x22, 0x71, 0x0a, 0x15, 0x49, 0x73, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x50,
	0x72, 0x61, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x69, 0x64, 0x73,
	0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x71, 0x0a, 0x13, 0x49, 0x73, 0x50, 0x72, 0x61, 0x69,
	0x73, 0x65, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x1a, 0x34, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x69, 0x73, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x69, 0x73, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x32, 0xf5, 0x01, 0x0a, 0x06, 0x50, 0x72,
	0x61, 0x69, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x50, 0x72, 0x61, 0x69, 0x73,
	0x65, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x61, 0x69, 0x73, 0x65, 0x2e, 0x41,
	0x64, 0x64, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x61, 0x69, 0x73, 0x65, 0x2e, 0x41, 0x64, 0x64,
	0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4e, 0x0a, 0x0c, 0x43,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x12, 0x1f, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x72, 0x61, 0x69, 0x73, 0x65, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x50,
	0x72, 0x61, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x72, 0x61, 0x69, 0x73, 0x65, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x54, 0x0a, 0x0e, 0x49,
	0x73, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x12, 0x21, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x61, 0x69, 0x73, 0x65, 0x2e, 0x49, 0x73, 0x50, 0x72, 0x61,
	0x69, 0x73, 0x65, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x61, 0x69, 0x73, 0x65, 0x2e, 0x49, 0x73,
	0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x42, 0x2c, 0x0a, 0x0a, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x61, 0x69, 0x73, 0x65, 0x50,
	0x01, 0x5a, 0x1c, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x72, 0x61, 0x69, 0x73, 0x65, 0x3b, 0x70, 0x72, 0x61, 0x69, 0x73, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_praise_praise_proto_rawDescOnce sync.Once
	file_api_praise_praise_proto_rawDescData = file_api_praise_praise_proto_rawDesc
)

func file_api_praise_praise_proto_rawDescGZIP() []byte {
	file_api_praise_praise_proto_rawDescOnce.Do(func() {
		file_api_praise_praise_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_praise_praise_proto_rawDescData)
	})
	return file_api_praise_praise_proto_rawDescData
}

var file_api_praise_praise_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_praise_praise_proto_goTypes = []interface{}{
	(*AddPraiseRequest)(nil),        // 0: api.praise.AddPraiseRequest
	(*AddPraiseReply)(nil),          // 1: api.praise.AddPraiseReply
	(*CancelPraiseRequest)(nil),     // 2: api.praise.CancelPraiseRequest
	(*CancelPraiseReply)(nil),       // 3: api.praise.CancelPraiseReply
	(*IsPraisePraiseRequest)(nil),   // 4: api.praise.IsPraisePraiseRequest
	(*IsPraisePraiseReply)(nil),     // 5: api.praise.IsPraisePraiseReply
	(*AddPraiseReplyData)(nil),      // 6: api.praise.AddPraiseReply.data
	(*CancelPraiseReplyData)(nil),   // 7: api.praise.CancelPraiseReply.data
	(*IsPraisePraiseReplyData)(nil), // 8: api.praise.IsPraisePraiseReply.data
}
var file_api_praise_praise_proto_depIdxs = []int32{
	0, // 0: api.praise.Praise.AddPraise:input_type -> api.praise.AddPraiseRequest
	2, // 1: api.praise.Praise.CancelPraise:input_type -> api.praise.CancelPraiseRequest
	4, // 2: api.praise.Praise.IsPraisePraise:input_type -> api.praise.IsPraisePraiseRequest
	1, // 3: api.praise.Praise.AddPraise:output_type -> api.praise.AddPraiseReply
	3, // 4: api.praise.Praise.CancelPraise:output_type -> api.praise.CancelPraiseReply
	5, // 5: api.praise.Praise.IsPraisePraise:output_type -> api.praise.IsPraisePraiseReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_praise_praise_proto_init() }
func file_api_praise_praise_proto_init() {
	if File_api_praise_praise_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_praise_praise_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPraiseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_praise_praise_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPraiseReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_praise_praise_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelPraiseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_praise_praise_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelPraiseReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_praise_praise_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsPraisePraiseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_praise_praise_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsPraisePraiseReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_praise_praise_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPraiseReplyData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_praise_praise_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelPraiseReplyData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_praise_praise_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsPraisePraiseReplyData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_praise_praise_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_praise_praise_proto_goTypes,
		DependencyIndexes: file_api_praise_praise_proto_depIdxs,
		MessageInfos:      file_api_praise_praise_proto_msgTypes,
	}.Build()
	File_api_praise_praise_proto = out.File
	file_api_praise_praise_proto_rawDesc = nil
	file_api_praise_praise_proto_goTypes = nil
	file_api_praise_praise_proto_depIdxs = nil
}
