// Code generated by entc, DO NOT EDIT.

package commentcount

import (
	"time"
)

const (
	// Label holds the string label denoting the commentcount type in the database.
	Label = "comment_count"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPraiseNum holds the string denoting the praise_num field in the database.
	FieldPraiseNum = "praise_num"
	// FieldReplyNum holds the string denoting the reply_num field in the database.
	FieldReplyNum = "reply_num"
	// FieldDislikeNum holds the string denoting the dislike_num field in the database.
	FieldDislikeNum = "dislike_num"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the commentcount in the database.
	Table = "comments_count"
)

// Columns holds all SQL columns for commentcount fields.
var Columns = []string{
	FieldID,
	FieldPraiseNum,
	FieldReplyNum,
	FieldDislikeNum,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPraiseNum holds the default value on creation for the "praise_num" field.
	DefaultPraiseNum uint32
	// DefaultReplyNum holds the default value on creation for the "reply_num" field.
	DefaultReplyNum uint32
	// DefaultDislikeNum holds the default value on creation for the "dislike_num" field.
	DefaultDislikeNum uint32
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(uint64) error
)
