// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CommentsColumns holds the columns for the "comments" table.
	CommentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "uid", Type: field.TypeUint64},
		{Name: "relation_id", Type: field.TypeUint64},
		{Name: "reply_to_uid", Type: field.TypeUint64, Default: 0},
		{Name: "relation_type", Type: field.TypeUint32},
		{Name: "parent_id", Type: field.TypeUint64, Default: 0},
		{Name: "belong_comment_id", Type: field.TypeUint64, Default: 0},
		{Name: "content", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CommentsTable holds the schema information for the "comments" table.
	CommentsTable = &schema.Table{
		Name:       "comments",
		Columns:    CommentsColumns,
		PrimaryKey: []*schema.Column{CommentsColumns[0]},
	}
	// CommentsCountColumns holds the columns for the "comments_count" table.
	CommentsCountColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "praise_num", Type: field.TypeUint32, Default: 0},
		{Name: "reply_num", Type: field.TypeUint32, Default: 0},
		{Name: "dislike_num", Type: field.TypeUint32, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CommentsCountTable holds the schema information for the "comments_count" table.
	CommentsCountTable = &schema.Table{
		Name:       "comments_count",
		Columns:    CommentsCountColumns,
		PrimaryKey: []*schema.Column{CommentsCountColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CommentsTable,
		CommentsCountTable,
	}
)

func init() {
	CommentsTable.Annotation = &entsql.Annotation{
		Table: "comments",
	}
	CommentsCountTable.Annotation = &entsql.Annotation{
		Table: "comments_count",
	}
}
